name: flutter_ffi_template
description: "flutter ffi template"

environment:
  sdk: ^3.8.0
  flutter: '>=3.3.0'

dependencies:
  ffigen: ^19.0.0
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffi: ^2.1.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

################################ flutter #######################################
flutter:
  plugin:
    platforms:
      windows:
        ffiPlugin: true

################################ ffigen #########################################
# Run with `dart run ffigen`
ffigen:
  name: "flutter_ffi_template"
  description: "bindings"
  output: "lib/bindings.dart"

  llvm-path:
    - C:\ProgramFiles\Library\clangllvm

  headers:
    entry-points:
      - "src/native/common.h"
      - "src/native/export.h"
    include-directives:
      - "src/**"

  # eliminate some warnings
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
